name: 🚀 Feature Request
description: Suggest an idea for AdaSeq
title: "[Feature] "
labels: ['feature request']

body:
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: addtion
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
